#+TITLE: Windows key mappings for Emacs
#+OPTIONS: num:nil

* About

This windows registry entry maps the control keys in such a way that
the (in Emacs) often-used =Ctrl= key comes to lie right next to the
space bar and the =Alt= key right next to it, to the right and the
left of the space bar. This way, there is symmetry in using those keys
with the right and the left hand, and the =Ctrl= keys can be typed by
curling your thumb. Additionally, =CAPS= is mapped to an additional
=Ctrl=, making it very accessible by using the left pinky.

Because the original left =Ctrl= key is left in place, most Windows
key combinations work like usual. If you're switching between Windows
and Mac, you can configure a similar mapping in macOS's Keyboard
Settings, having =Cmd= in the same location as =Ctrl= on Windows.  In
effect, this allows you to type the same physical key combination for
=Ctrl-V= and =Cmd-V= on both systems, respectively.

The =App= key on serves as a =AltRight= key, making key combinations
for international characters accessible when using the
/US-International/ or German keyboard layout, for example. Finally,
the right =Ctrl= key becomes the =Win= key. Be aware that some laptop
keyboards might not have the right =Ctrl= key, preventing the use of
the =Win-L= combination to lock your screen, for example.

** Caveats

- The changes only take effect after a reboot
- all users of the computer are affected by these changes
- =Ctrl-Alt-Delete= works differently because of the changed location
  of the =Alt= key (might upset IT staff)
- =Win= combinations (e.g. =Win-L= to lock screen) now use the right
  =Ctrl= key
- =App= key is disabled
- =CAPS= is disabled
- =AltRight= (e.g. for US-Intl key combinations) is the key labeled
  =App=

* Registry Entry

The key mappings are done on a low system level using the Windows scan
code mapper, so no additional drivers are needed.

** Registry Entry file

[[./KeyMapping.reg][Download]] the =.reg= file (or copy the text below into an appropriate
file) and run it (i.e. merge it with your local registry).

#+INCLUDE: "./KeyMapping.reg" example

** Explanation

This [[https://msdn.microsoft.com/en-us/library/windows/hardware/jj128267(v=vs.85).aspx#scan_code_mapper_for_keyboards][MSDN article]] explains the configuration of the scan code
mapper. The most accurate table of scan codes I could find can be
seen [[http://www.winfaq.de/faq_html/Content/tip1500/onlinefaq.php?h=tip1576.htm][here]].

For reference, these are the mappings used in the registy entry, in
the order they occur in the entry's byte sequence:

| Pos | from        | Scan code | to          | Scan code |
|-----+-------------+-----------+-------------+-----------|
|  1. | =CAPS=      | ~3a 00~   | =CtrlLeft=  | ~1d 00~   |
|  2. | =WinLeft=   | ~5b e0~   | =AltLeft=   | ~38 00~   |
|  3. | =AltLeft=   | ~38 00~   | =CtrlLeft=  | ~1d 00~   |
|  4. | =AltRight=  | ~38 e0~   | =CtrlRight= | ~1d e0~   |
|  5. | =WinRight=  | ~5c e0~   | =AltLeft=   | ~38 00~   |
|  6. | =App=       | ~5d e0~   | =AltRight=  | ~38 e0~   |
|  7. | =CtrlRight= | ~1d e0~   | =WinLeft=   | ~5b e0~   |

** Remove keyboard mappings

Remove all scan code mappings with [[./RemoveKeyMapping.reg][this]] entry:

#+INCLUDE: "~/github/win-keys/RemoveKeyMapping.reg" example
